runtime: python27
api_vesion: 1
thredsafe: true

handlers:
  -url: /
  static_files: DTDM/index.html
  upload: DTDM/index.html

  -url: /(.*)
   static_files: DTDM/\1
   upload: DTDM/(.*)
